### ISSUE TITLE
java.lang.NoSuchMethodError after updating videobridge and jicofo

### ISSUE THREAD

**Issue by oguzozturk** [jitsi/jitsi-meet#15589]
### What happened?

After upgrade jitsi web from  jitsi-meet 1.0.6991 to jitsi-meet 1.0.8187 including jicofo and videobridge, I have got the following error:

JVB 2025-02-10 16:15:49.733 INFO: [1] JitsiConfig.<clinit>#47: Initialized newConfig: merge of /etc/jitsi/videobridge/jvb.conf: 1,application.conf @ jar:file:/usr/share/jitsi-videobridge/jitsi-videobridge.jar!/application.conf: 1,system properties,reference.conf @ jar:file:/usr/share/jitsi-videobridge/jitsi-videobridge.jar!/reference.conf: 1,reference.conf @ jar:file:/usr/share/jitsi-videobridge/lib/ice4j-3.0-72-g824cd4b.jar!/reference.conf: 1,reference.conf @ jar:file:/usr/share/jitsi-videobridge/lib/jitsi-media-transform-2.3-105-ge155b81e.jar!/reference.conf: 1,reference.conf @ jar:file:/usr/share/jitsi-videobridge/lib/jitsi-media-transform-2.3-165-gb7dba824.jar!/reference.conf: 1
JVB 2025-02-10 16:15:49.772 INFO: [1] ReadOnlyConfigurationService.reloadConfiguration#51: loading config file at path /etc/jitsi/videobridge/sip-communicator.properties
JVB 2025-02-10 16:15:49.783 INFO: [1] JitsiConfig.<clinit>#68: Initialized legacyConfig: sip communicator props (no description provided)
JVB 2025-02-10 16:15:50.283 INFO: [1] JvmMetrics.<init>#36: Detected GC type G1
JVB 2025-02-10 16:15:50.313 INFO: [1] MetricsUpdater.addUpdateTask#45: Scheduling metrics update task with interval PT5S.
JVB 2025-02-10 16:15:50.377 SEVERE: [1] MainKt.main$lambda$0#56: An uncaught exception occurred in thread=Thread[main,5,main]
java.lang.NoSuchMethodError: 'void org.jitsi.nlj.RtpReceiverImpl$Companion.setQueueErrorCounter(org.jitsi.utils.queue.CountingErrorHandler)'
        at org.jitsi.videobridge.metrics.QueueMetrics.init(QueueMetrics.kt:51)
        at org.jitsi.videobridge.metrics.Metrics.start(Metrics.kt:47)
        at org.jitsi.videobridge.MainKt.main(Main.kt:71)
        at org.jitsi.videobridge.MainKt.main(Main.kt)

![Image](https://github.com/user-attachments/assets/156b53f2-5c6e-4ac7-923f-493f5f349054)

### Platform

- [x] Chrome (or Chromium based)
- [x] Firefox
- [x] Safari
- [ ] Other desktop browser
- [x] Android browser
- [x] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Jitsi Meet 2.0.9753 (2024-09-25) 

### Relevant log output

```shell
[conference.js] <f2._onConferenceFailed>:  CONFERENCE FAILED: conference.videobridgeNotAvailable
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
Did you have some manual modifications in the previous running bridge?

**Comment by oguzozturk** [comment]
We did not fork the project, we only have config changes, I can share the config if you want.

**Comment by damencho** [comment]
Can you check the files in /usr/share/jitsi-videobridge/libs folder, check the dates is there anything that seems different?

**Comment by oguzozturk** [comment]
Problem solved after upgrading operation system from Debian 10 to 12, and setting up jitsi from the beginning. We think that there was a package incompatibility when updating the old operating system.
