### ISSUE TITLE
BackHandler.removeEventListener Error | React-Native 0.77+

### ISSUE THREAD

**Issue by jplandry908** [jitsi/jitsi-meet#15864]
### What happened?

After upgrading from react-native 0.76 to 0.77, errors are generated due to the use of  "BackHandler.removeEventListener". It appears 'removeEventListener' was removed in 0.77.

https://reactnative.dev/docs/0.76/backhandler
vs
https://reactnative.dev/docs/0.77/backhandler

I have identified its use in 3 locations, all related to the 'hardwareBackPress' event  listener.

react/features/prejoin/components/native/Prejoin.tsx
react/features/base/react/components/native/SlidingView.tsx
react/features/conference/components/native/Conference.tsx

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [x] Android mobile app
- [x] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

@jitsi/react-native-sdk@11.1.2

### Relevant log output

```shell
arning: TypeError: _reactNative.BackHandler.removeEventListener is not a function (it is undefined)

This error is located at:
    in Prejoin (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View (created by Animated(View))
    in Animated(View) (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View (created by Animated(View))
    in Animated(View) (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by StackView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by RootNavigationContainer)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by RootNavigationContainer)
    in RootNavigationContainer (created by Connect(RootNavigationContainer))
    in Connect(RootNavigationContainer) (created by App)
    in RCTView (created by View)
    in View (created by DimensionsDetector)
    in DimensionsDetector (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in Provider (created by App)
    in I18nextProvider (created by App)
    in ThemeProvider (created by PaperProvider)
    in RCTView (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by PaperProvider)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by PaperProvider)
    in PaperProvider (created by JitsiThemePaperProvider)
    in JitsiThemePaperProvider (created by App)
    in App
    in RCTView (created by View)
    in View
    in Unknown (created by Jitsi)
    in Jitsi (created by Connect(Jitsi))
    in Connect(Jitsi) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by StackNavigator)
    in RCTView (created by View)
    in View (created by CardContainerInner)
    in RCTView (created by View)
    in View (created by CardContainerInner)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View (created by Animated(View))
    in Animated(View) (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View (created by Animated(View))
    in Animated(View) (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainerInner)
    in CardContainerInner (created by CardStack)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack), js engine: hermes
```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
We currently don't support RN > 0.75. We'll solve the incompatibilities once we update our base version.

**Comment by jplandry908** [comment]
FYI - If anyone wants to update react-native to v0.77 (accepting the risk) before jitsi officially supports it, this patch should resolve this error.

[@jitsi+react-native-sdk+11.1.2.patch](https://github.com/user-attachments/files/19536810/%40jitsi%2Breact-native-sdk%2B11.1.2.patch)

**Comment by jplandry908** [comment]
FYI - If anyone else wants to upgrade to react-native v0.77 (at risk) prior to Jitsi officially supporting it, this patch should resolve this error.

[@jitsi+react-native-sdk+11.1.2.patch](https://github.com/user-attachments/files/19536892/%40jitsi%2Breact-native-sdk%2B11.1.2.patch)

**Comment by jplandry908** [comment]
FYI - If anyone else wants to upgrade to react-native v0.77 (at risk) prior to Jitsi officially supporting it, this patch should resolve this error.

[@jitsi+react-native-sdk+11.1.2.patch](https://github.com/user-attachments/files/19537036/%40jitsi%2Breact-native-sdk%2B11.1.2.patch)

**Comment by saghul** [comment]
A PR would be welcome!

**Comment by jplandry908** [comment]
https://github.com/jitsi/jitsi-meet/pull/15868

**Comment by jplandry908** [comment]
Here you go! 

https://github.com/jitsi/jitsi-meet/pull/15874
