### ISSUE TITLE
jitsimeet issue when run on ios 12.0

### ISSUE THREAD

**Issue by vineethnkforios** [jitsi/jitsi-meet#10759]
Working fine in ios iOS 13.0, 14.4 but not working in iOS 12.0

Crashes with the log as follows:

dyld: Symbol not found: _OBJC_CLASS_$_RPSystemBroadcastPickerView

  Referenced from: /Users/everosmacmini/Library/Developer/Xcode/DerivedData/DIGITALAgency-cypoajwjiebtkgcaclsibsmbloku/Build/Products/Debug-iphonesimulator/JitsiMeetSDK.framework/JitsiMeetSDK

  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/ReplayKit.framework/ReplayKit

in /Users/everosmacmini/Library/Developer/Xcode/DerivedData/DIGITALAgency-cypoajwjiebtkgcaclsibsmbloku/Build/Products/Debug-iphonesimulator/JitsiMeetSDK.framework/JitsiMeetSDK

dyld: launch, loading dependent libraries

DYLD_FRAMEWORK_PATH=/Users/everosmacmini/Library/Developer/Xcode/DerivedData/DIGITALAgency-cypoajwjiebtkgcaclsibsmbloku/Build/Products/Debug-iphonesimulator

DYLD_FALLBACK_LIBRARY_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib

DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot

DYLD_FALLBACK_FRAMEWORK_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks

DYLD_INSERT_LIBRARIES=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 12.4.simruntime/Contents/Resources/RuntimeRoot/Developer/Libr

Any solution ?

### Steps to reproduce:

1. 
2. 
3. 

### Server information:

- Jitsi Meet version:4.0
- Operating System:iOS 12.0

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
That's odd, RPSystemBroadcastPickerView should be available on iOS 12. Any ideas @alexbumbu ?

**Comment by vineethnkforios** [comment]
Any soultions @saghul ?

**Comment by saghul** [comment]
I have no idea, sorry.

**Comment by vineethnkforios** [comment]
Any soultions @alexbumbu ?

**Comment by vineethnkforios** [comment]
Got one link with same issue
https://fromatom.hatenablog.com/entry/2020/10/19/164905 
Did the same but not resolved

**Comment by alexbumbu** [comment]
> That's odd, RPSystemBroadcastPickerView should be available on iOS 12. Any ideas @alexbumbu ?

Yeah, but we disabled it because our trick in js to show the broadcast picker didn't work on iOS 12. Why it's crashing though, I don't know.

**Comment by saghul** [comment]
@vineethnkforios I noticed the failure is when building for a simulator. Have you tried building for a real device? I regularly test on iOS 12 on a real device and have observed no issues.

**Comment by erdemaknc** [comment]
@vineethnkforios Same issue occured 2 diffrent ios version iphone 6 12.5.5,  iphone 6 15.3.1 . Did you find any solution?

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by riazhazan** [comment]
The issue is even happening with latest Xcode 12.3 and iOS 12 simulators.

**Comment by saghul** [comment]
Sorry, we have no time to look into old iOS versions, specially simulators. AFAICT this works on real devices. If you find a fix, a patch would be welcome.
