### ISSUE TITLE
@jitsi/react-native-sdk does not work with React Native 0.74.3

### ISSUE THREAD

**Issue by danchily2** [jitsi/jitsi-meet#14912]
### What happened?

The issue seems to be cause by **@react-native-community/clipboard** dependency which is outdate.
Is it possible to remove this dependency from @jitsi/react-native-sdk  ?

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [X] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

 "@jitsi/react-native-sdk": "^2.2.1"

### Relevant log output

```shell
Projects/event-native-app/event-native-app/node_modules/@react-native-community/clipboard/android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java:14: error: cannot find symbol
import com.facebook.react.bridge.ContextBaseJavaModule;
                                ^
  symbol:   class ContextBaseJavaModule
  location: package com.facebook.react.bridge
Projects/event-native-app/event-native-app/node_modules/@react-native-community/clipboard/android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java:23: error: cannot find symbol
public class ClipboardModule extends ContextBaseJavaModule {
                                     ^
  symbol: class ContextBaseJavaModule
Projects/event-native-app/event-native-app/node_modules/@react-native-community/clipboard/android/src/main/java/com/reactnativecommunity/clipboard/ClipboardPackage.java:23: error: incompatible types: ClipboardModule cannot be converted to NativeModule
    modules.add(new ClipboardModule(reactContext));
                ^
Projects/event-native-app/event-native-app/node_modules/@react-native-community/clipboard/android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java:31: error: method does not override or implement a method from a supertype
  @Override
  ^
Projects/event-native-app/event-native-app/node_modules/@react-native-community/clipboard/android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java:37: error: cannot find symbol
    return (ClipboardManager) getContext().getSystemService(getContext().CLIPBOARD_SERVICE);
                                                            ^
  symbol:   method getContext()
  location: class ClipboardModule
Projects/event-native-app/event-native-app/node_modules/@react-native-community/clipboard/android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java:37: error: cannot find symbol
    return (ClipboardManager) getContext().getSystemService(getContext().CLIPBOARD_SERVICE);
                              ^
  symbol:   method getContext()
  location: class ClipboardModule
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
6 errors

FAILURE: Build failed with an exception.

```
```


### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

_No response_

**Comment by saghul** [comment]
We have updated all dependencies and made the SDK compatible with RN 0.73, the release will be coming soon.

**Comment by serifkazan** [comment]
Hi same issue after release 10.0.0.

I changed "ContextBaseJavaModule" with "ReactContextBaseJavaModule" but after that i get "Type com.reactnativecommunity.clipboard.BuildConfig is defined multiple times:"

**Comment by saghul** [comment]
We use 0.73, not 0.74. More changes are likely needed.

**Comment by aemre** [comment]
remove old clipboard. install **@react-native-clipboard/clipboard**
and install patch-package.
add package.json script:    `"postinstall": "patch-package"`
**node_modules/@jitsi/react-native-sdk/react/features/base/util/copyText.native.ts** change like.
```
import Clipboard from '@react-native-clipboard/clipboard';
/**
 * Tries to copy a given text to the clipboard.
 * Returns true if the action succeeds.
 *
 * @param {string} textToCopy - Text to be copied.
 * @returns {Promise<boolean>}
 */
export function copyText(textToCopy: string) {
    try {
        Clipboard.setString(textToCopy);

        return true;
    } catch (e) {
        return false;
    }
}
```
and patch.
