### ISSUE TITLE
After Updating Flutter to Version 3.0 The Jitsi mEet is not Running in Compiler.

### ISSUE THREAD

**Issue by shaheryarbabar** [jitsi/jitsi-meet#11546]
### Description:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jitsi_meet:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

### Steps to reproduce:

1. Open visual Studio code
2. Then After Updating FLutter 2.10 to 3.0 Type Flyutter Run in Terminal
3. Error Came  Execution failed for task ':jitsi_meet:compileDebugKotlin'.

### Expected behavior:

It Should Run Smooth

### Actual behavior:
Execution failed for task ':jitsi_meet:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

### Server information:

- Jitsi Meet version: 4.0
- Operating System: Windows 11

### Client information:

- Browser / app version: Flutter3.0
![Screenshot_1](https://user-images.githubusercontent.com/50921452/168977400-60227670-3eb7-4e35-aefc-325d57020839.png)

- Operating System: Windows 11

**Comment by saghul** [comment]
Sorry, we are not the maintainers of that module, please ask the author.

**Comment by ashisha43** [comment]
i am also facing the same issue please give us solution

**Comment by shaheryarbabar** [comment]
@ashisha43   i've solved the issue. You have to remove the version in pubspe and add these

jitsi_meet:
    git:
      url: https://github.com/dispersik/jitsi_meet_fork
      ref: master

![Screenshot_5](https://user-images.githubusercontent.com/50921452/172093438-ac38404f-afd8-4df8-a693-6278450372fe.png)

and then run the pub get.  I am attaching a Screenshot of how to do that

**Comment by sohelakhtar23** [comment]
# error fixed
From the <b>VS code, </b>
go to  Dependencies> direct dependencies> jitsi_meet> android\src\main\kotlin\com\gunschu\jitsi_meet\JitsiMeetPlugin.kt file

<b>as shown in the below figure</b>
![jitsi_error_fixed](https://user-images.githubusercontent.com/45822078/174290463-dbab6d33-63da-4cbc-ae83-e88776a8746b.PNG)

go to line 34, add <b>a ? after Activity</b> as shown below and the error will be fixed
![image](https://user-images.githubusercontent.com/45822078/174291031-b5574c5a-9e2a-4bd5-859e-d640c5471642.png)

    constructor(activity: Activity?) : this() {

**Comment by khalidchaudry** [comment]
[sohelakhtar23](https://github.com/sohelakhtar23) my problem solved thanks dear.

**Comment by Kangajan18** [comment]
@shaheryarbabar , its' working bro, Thank you very much

**Comment by saleemaperidot** [comment]
hey !!!! its working
