### ISSUE TITLE
Unable to integrate Jitsi-meet in iOS project

### ISSUE THREAD

**Issue by laxminarayanmn** [jitsi/jitsi-meet#3562]
There are many errors at different times, like:

- WebRTC not found, even if we followed all the steps mentioned [here](https://github.com/jitsi/jitsi-meet/tree/master/ios)
- The following build commands failed:
`Ld /Users/…/Library/Developer/Xcode/DerivedData/jitsi-meet-aaflvloqddxmfjczgfklqpihixfs/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Objects-normal/armv7/JitsiMeet normal armv7
(1 failure)`

If ever the archive succeeds then in the project it gives the following errors:

- Enable Bit Code error
- Missing arm64 architecture error

We tried solution given [here](https://github.com/jitsi/jitsi-meet/issues/3514) with no luck.

Could you please suggest some solution for this?

Xcode: v10
Node: v10.12.0
react-native-cli: v2.0.1

**Comment by saghul** [comment]
Hi there!

Looks like Xcode 10 broke something. My current suggested workaround if to build the Jitsi Meet app and take the framework off of it.

I’ll add this to the docs, thanks for the feedback!

**Comment by elliscwc** [comment]
@saghul 
i'm getting this error 
`dyld: Symbol not found: __T0BOWV`
when using xcode10, xcode9 works fine for me, something to do with Swift 4.2?

**Comment by atalayasa** [comment]
I am using xCode 10 and it gave me an error 

> Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /Users/atalayasa/Downloads/Saglik/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/x86_64.swiftmodule
Are there any solution about it what shall I do for not to get that error?

**Comment by saghul** [comment]
@elliscwc I have never seen that error, sorry.

**Comment by saghul** [comment]
@atalayasa Where did you get JitsiMeet.framework from?

**Comment by atalayasa** [comment]
@saghul Actually I get it from Github and it was forking fine until I installed xCode 10.0 version.

**Comment by saghul** [comment]
You need to rebuild the framework with Xcode 10 too.

**Comment by elliscwc** [comment]
@saghul thanks, it works after rebuild!

**Comment by safilsunny** [comment]
we are facing the same issue in Xcode 10.1 and would be nice if you can share the steps 

@saghul and @elliscwc

**Comment by saghul** [comment]
@safilsunny Have you rebuilt the Jitsi Meet framework? That's all that you should need. If that doesn't work, build the Jitsi Meet app and extract the framework from there, Xcode 10 had some problems with the framework target and I haven't tested 10.1 yet to confirm this was fixed.

**Comment by safilsunny** [comment]
@saghul managed to solve the issue by building the framework in Xcode 10.1.
