### ISSUE TITLE
Failed resolution of: Lcom/dropbox/core/android/Auth;

### ISSUE THREAD

**Issue by Anasmirza20** [jitsi/jitsi-meet#16571]
### What happened?

After updating the JItsi to 11.6.3, the app started crashing. 

Here is the stack trace of this crash 
` java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dropbox/core/android/Auth;
                                                                                                    	at org.jitsi.meet.sdk.DropboxModule.onHostResume(DropboxModule.java:185)
                                                                                                    	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:261)
                                                                                                    	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:859)
                                                                                                    	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:894)
                                                                                                    	at com.facebook.react.ReactInstanceManager.lambda$setupReactContext$3(ReactInstanceManager.java:1299)
                                                                                                    	at com.facebook.react.ReactInstanceManager.$r8$lambda$pu7uI5W8XB5vLxNQmijLRH5XPtQ(Unknown Source:0)
                                                                                                    	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda4.run(D8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257)
                                                                                                    	at android.os.Looper.loop(Looper.java:368)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dropbox.core.android.Auth" on path: DexPathList[[zip file "/data/app/~~Cj_Jp3RgzL5hCeUXT1_ZtQ==/com.quickhealthpatient-1EiA3jz04bsnhM3zaN-lUQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~Cj_Jp3RgzL5hCeUXT1_ZtQ==/com.quickhealthpatient-1EiA3jz04bsnhM3zaN-lUQ==/lib/arm64, /data/app/~~Cj_Jp3RgzL5hCeUXT1_ZtQ==/com.quickhealthpatient-1EiA3jz04bsnhM3zaN-lUQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)`

### Platform

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [x] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Jitsi version : 11.6.3

### Relevant log output

```shell

```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by Aayushdev18** [comment]
Hi, I’d like to work on this issue. Could you please assign it to me?

**Comment by Anasmirza20** [comment]
I don't have an option to assign. If you know how to fix this, please let me know.... @Aayushdev18

**Comment by Anasmirza20** [comment]
@saghul can you please provide the update on this?

**Comment by Aayushdev18** [comment]
@Anasmirza20 I think this is a missing dependency issue. The Jitsi Meet SDK is trying to use Dropbox functionality but the required Dropbox Core Android library isn't included in your app

**Comment by Anasmirza20** [comment]
We already have the 2 Dropbox dependencies

`   
 implementation 'com.dropbox.core:dropbox-core-sdk:7.0.0'
 implementation 'com.dropbox.core:dropbox-android-sdk:7.0.0'
`

What else do I need to add?
