### ISSUE TITLE
cannot find type 'PiPViewCoordinator' in scope

### ISSUE THREAD

**Issue by PawanRamteke** [jitsi/jitsi-meet#10383]
Hello Team,

I am working on jitsi_meet 4.0.0 and got errors

1. cannot find type 'PiPViewCoordinator' in scope
2. 'nil' requires a contextual type pipViewCoordinator = nil

I am using android studio.

Please check this issue and revert ASAP. 

Thanks

**Comment by saghul** [comment]
PiPViewCoordinator is an iOS thing, and you say you are using Android Studio?

**Comment by PawanRamteke** [comment]
Yes, but I am trying running on iOS simulator from android studio.
Please find attached screenshot.

<img width="1680" alt="Screenshot 2021-11-17 at 4 08 33 PM" src="https://user-images.githubusercontent.com/17869441/142185276-b5d0163e-0deb-421e-a14f-45a4ab242a1a.png">

**Comment by saghul** [comment]
Do you see the same issue with Xcode? We don't support anything other than Xcode for working in the iOS codebase.

**Comment by PawanRamteke** [comment]
Yes Its working with xcode. But not with Android studio or VS code tool.

**Comment by saghul** [comment]
Sorry, we don't support those tools for iOS development. If you find a fix yourself a PR would be welcome though.
